vips:
  - vip: 192.168.67.2
    port: 80
    proto: 6 # TCP
    real_servers:
      - addr: 192.168.67.3
        port: 80
      - addr: 192.168.67.3
        port: 80
      - addr: 192.168.67.3
        port: 80